import time
daDesktop = """\MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyyyyyho+++++++dMMMNymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNMmmmmmh/-y+:ohdyyyyyyddddddddNMMMh+oMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMNNdmMMMMMNhdMMMMMdyMMMMMmdMmmmmmmmmNNmNNMMMMMMMMMMMMMMMMMMMM+/mMMMNo://s/sddddoomo////NydmdNNNNNNNmNNMMMMMMMMNNMMMMMMMMMMMMMN+o+////dNs++/+mMMhydmMMMMysmm/++/oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyyyyyyo+::sy::-+MMMMMMmmMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmNNmsydmmmmddddmdmddddddddddddmhdmdmmmmmmmmNNNNmNNNmmmmmmmmmmmmmNmdhmdyyyyyymNmdhssNMh:/:oNMMMNyNNyss++mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdddddyhhhhhhy+osssssymmNNmmmNMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNhmNNNNmdNmmmmmmmmmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmNmmmmmNNNNmmmmNmmmmmmmmmmmmmmmNmNmmmmNNNNmmmmNmNNNNddmdmNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNMMMMMMMMNMMMMMNNNNNNNNNNNNNmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNmmmmmmmNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNmmmmmmmmmmmmmmmmmmmmmmmNmNNmmmmmmmmmmmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNmmNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNhsssshNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmdss--/:/:::/+oshmddddddmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNmNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmddmmmmmmmmdmddmmddddmmmmmmdmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddMNh:/:+sshmddddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddmmmmddddddddddddddddddddddddddddddddddddddddddmmmmmdddmmmmdddddddddddddddddhhddddddddddddddddddddddddddmmmdmdmmdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMddddyhhy+dy-/dddydmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddmmmdddddddddddddddddddddhddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddhhddddNNNMMMNhsdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM::::/mymhmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddddddddddddddddddddddhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddmdo::-:dddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddmmmdddddddddddmdddddddddddddddddddddddddhhddhddhhhhhhhhhhhhhhyyhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhdddhsoy/-/yo/ssshNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdmMmNdhNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhdhhhhhhhhhhhhhhhhhhhhhhhhhhyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyhhhhhhhhhhhhhhhhhhhhdhydddds/-:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd+:.:mhdddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddddddddddddddddddddddddddddddddddddddhhhhdhhhhhhhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhhhhs+-+shddddddmmmmmmmmmmmmmmmmmmmmmdddmmmmddddddddddhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhddmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMN+-//:hodddmmmmddmmmmmmmmmmmmmmmmmmdddddddddddddhhhhhhhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyhhhhhyyyyyhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhyyyyhhhhyyhhhhhhhhhhhhhddNNMMMNMMmNyoshdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh:+ydohmmddmmmmmmmmmmmddddddddddddddddddddhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysyssyyyyysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhyyyyyyyyyyyyyyhhhhhhhhhhhhhhhddhddmmyo/-..:+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy:+mo/sdmmmmmmmmmmmmmmmdddddddddddddhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysyyssssyyysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyssssssyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhdmNNNdy//+ohsoohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+/+odNmmmmmmmmmmmmmmmmddddddddhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyssyysssssssssssssssssssssssssssssyyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyssssssssssssyyssyyyysssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhdmmhyyhyo:`-+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmo:/hdmmmmmmmmmmmmmdddddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssyyysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyssssssssssyysssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyyhhhhhhhhdmmNMNh:`./dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN./NhdmmmmmmddddddddddddhhhhhhhyyyyyyyyyyyyyyyyyyyysssyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoosssssssssssssssssssssssssssssssssssssssssssssssysssssssssssyysssyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhddNMNo:/+yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMho+:sdddmmmmmmdddddhhdhhhhhhhyyyyyyyyyyyyyyyyssssysssssssssssssssssssssssssssssssssssssssssoosssssssooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyyyyyhhhhhhhhhhhhhhhhhhdmNmy-`:mNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy/`:ohmdmmmmmmmddddhhhhhhhhhyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooosssoosssssssssssssssssssooooooooooooooossssssssoooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhyhmd/.`+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/.os+hdmmmmmmmddddhhhhhhhhhhhyyyyyysssssssssssssssssssssssssssssssssssssssssoosooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssoooosoosssssssooooosssssssssssssssssssssssssssssssssyyyyyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhyyhdNh:`oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`/yddmmmddddmdddhhhhhhhhhyyyyyyyyyyssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssosooooossooooooooooooossssssssssssssssssssssssssssssyyyyyssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhyyyyyhhyhhhhhhhhhhhhhhhhhhhhhhhhhhmd/`NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdms/sdddddddddddddhhhhhhhyyyyyyyyyyyyyyssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooo+++oooooooo+++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssyyysssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhys./MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMs--yyyydmmddddhddhhhhhhyyyyyyyyyyysssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++ooooooooooooooooooooo+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssssyysssyyysssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy+:+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMdosshddddddddhhhhhhhhhyyyyyyyyyyysssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++ooooooooo+++++++++++++++++++++++++++++oooooooooooooooo++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddhhhhhhhhhhhhy: +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMy``oshhdddddddhhhhyyyyyyyyyyyysssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+++++++++ooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddhhhhhhhy/-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMs/./yhhddddhhhhhhhyyyyyyyysssssssssssssssssssssoooooooooooooooo+++ooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//++++++////////////////++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooosssssssssssssssssssoosssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyhhhhhhhdhhhdddhhhddddddddddddddddmmmmmmmmmmmmmmmmmmddddddddddhys+./sdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMd- :yhhddddhhhhhhhyyysssssssssssssssssssoooooooooooooooooooooooo+++++oooo++++++++oo+++++++++++++++++++++++++++++++++++++++++++++++++++++/////////////////////////////////////////////////////////+++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooosssssooooooooosssoooooooooooossssssssssssssssssssssyyyyyyyyhhhhhhhhhhhhdddddddddddddmdddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddyy++::/hdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM` +hyddddddhhhhhhhyyysssssssssssssssssssooooooooooooooooooooooooo++++oooo++++++++++++++++++++++++++++++++++++++++++++++++////////////////////////////////////////////////////////////////////////////////+++++++++++++++++++++++o+++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssyysssyyyyyyyyhhhhhhhddddddddddddddddddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhyyyo:``-yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMd`.yyhdddddhhhhhhyyyyssssssssssssssssssssooooooooooooooooooooooooo++++++++++++o+++++++++++++++++++++++++++//////////////////////////////////////////://::://::::::::///////::::::::://////////////////////++++++++++++++++++++++++++++++++++oo+ooooooooooooooooooooooooooooooooooooosssossoooooooosssssssssssssyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhhhhyys+-.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMs-oyyhhhhhhhhhhhyyyyyssssssssssssssssssssooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++///////////////////////////////:::::::::::::::::::::::::::::::::::::::::::::::://///////////////////////++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooossssssssssooosssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhddddddddmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddhhhhydmhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM+/syhhhhhhhyyyyyyyyyyssssssssssssssssssssoooooooooooooooooooooooo++++++++++++++++++++++++++++++++++/////////////////////////////::::::::::::::::::::::::::::::::::::::::::::::::::::://////////////////////////////++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooosoooooossosssooooosssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyhhhhddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddhhddddhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMy/oyyyhyyyyyyyyyyyyyyysssssssssssssssssooooooooooooooooooooooooooo+++++++++++++++++++++++++++////////////////////////////:::::////::::::::::::::::::::::::::::::::::::::::::::::::::://////////://////////////////////////+++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosoooooooooooooosssssssssssssyyyyyyyyhhhhhhddddddddddddddddmmmmmmmmmmmmmmmmdddddddddddddddddddddddhhhdddmdhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNmy++syyhyyyyyyyyyyyyyyysssssssssssssssosssossssooooooooooooooooooooo+++++++++++++++++++++++/////////////////////////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://////////////////////////////////////+++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssssyyyyyyyyhhhhhhhdddddddddddddddddddddmmmmmdddddddddddddddddddddddddddddddddhddmmdhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMM/.oyyyyyyyyyyyyyyssssssssssssssssssssssoooooosssoooooooooooooooooooooo+++++++++++++++++//////////////////////////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://////////////////////////////////////+++++++++++++++++oooo+oo+++++ooooooooooooooooooooooooooooooooooooooooooo+++++++o+o+ooooooooooooosssssssssyyyyyyyyyyyyyhhhhhhhddddddddddddddddddddmmmmdmddddddddddddddddddddddddddddhhhhdddhddhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMN-:syyyyyyyyysssssssssssssssssssssssssssoooooossoooooooooooooooooooooooo+++++++++++++++///////////////:::///:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://:///////////////////////////////+++++++++++++++++++++++++++++++++++++++o+++++++++++++++++++++++++++++++++++++++o+ooooooooooooooossssssssssssyyyyyyyyyyyyyhhhhhhdddddddmmmmddmmmmddmmmmmmmmmdddddddddddddddddddhhhhddhhhdddddhyyosNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMh -ssyyyyyysssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooo++++++++++++///////////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://////////////////////////////++///++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+ooooooooooooosssssssssssyssyyyyyyyyyyyyyyhhhhdddddddmmmmmmmmmmmmmmmmmmmmmmddddddhhhddddddhhhhhhhdddhdddddhyso:`:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMs .osyyyyysssssssssssssssssssssssssssssoooooooooooooooooooooosoooooooooo++++++++++++++////////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::///////////////////////////////++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooossssssssssssssssyyyyyyyyyyyyyyyyyyhhhhhhdddddmmmmmmmmmmmmmmmmmmmmmmmddddddhhdddhhhhhhhhhdddddddddhys+:. :ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM+-:ossyyyssssssssssssssssssssssssssssoossssoosssoooooooooooooooooooooooo++++++++++++++////////////::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::////////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o++oooooooooooooooosssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyhhhhhddddddmmmmmmmmmmmmmmmmmmmmmdddddddddddddhhhhhhhddddddddhhyo+/:   .yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs:oosssyssssssssssssssssssssssssssssssoosssssssooosssoooooooosoooooooooooo++++++++++++///////////////::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::////////////////////////////++++///+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooosssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhdddddmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddddhyyo+/:::   .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMh.:oossysssssssssssssssssssssssssssssssssooooooooooossoooooooooooooooooooooo++++++++++++++////////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://///////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooosssssssssssssssssyyyyyhhhyyyhhhhhyhhhyyyyyyyhyyhhhhhhhhhhhhddddddmmmmmmmmmmmmmNmmmmmmmmdddddddddddddddddddddddhdddhhhyso+/////:`./dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMs /ossyssssssssssssssssssssssssssssssssssooooooooosssooooooooooooooooooooooooo++ooo+++++++++//////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::///////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooosssssssssssssssssssyyyyyyyhhhhhhhhhhhhhhhhdhhhhhhhhhhhdddddddddddddddmmmmmmNNNNNNNNNNNmmmmmmddddddddddddddddddddddddhhhddhhhhyssoooooo+/:/yhmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMm+.`ossssssssssssssssssssssssssssossooooooooooooooosossoooooooooooooooooooooooooooooooo+++++++++/////////:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::////////////////////////+++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooosssssssssssssssssssssyyyyyyyyyhhhhhhhhhhhhhhhdddhhhhhhhhhddddddddddddddddddmmmmmNNNNNNNNmmmmmmmmddddddddddddddddddddddhhhhhhhhhhhyyyyyyysssoo+++/-//symmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMd` -ssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooosooooooooooooooooooo++++++++++/////////////////////:::::::::::::::::::::::::::::::::///////:::///:::::://///////////////////////++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooosssssssssssssssssssssssssyyyyyyyyyhhhhhhhhhhhhhhhhhyyyyyhhhhhhhhhhhhhhhhdddddmmmmmNNNNNNNmmmmmmmmmmmmdmmdddddddddhhhhhhhhhhhhhhhhyyyyyyyyssssssssssooooo++os+dmmmmmmmNdhydNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMmo--ossssssssssssssssssssssssssssssssssoooooooosssssoooooooooooooooooooooooooooooooooooooooo+++++++++////////////////////////////////////////////////////////////////////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooossssssssssssssssssssssssssssyyyyyyyyyyyhhyyyyhhhhhhhhhyyyyhhhhhhhhhhhhhhhdddddmmmmmmNNNNmmmmmmmmmmmmmmmmmmdddddddhhhhhhhhhhhyyyyyyyyyyysssssssssssssssssooo+o+++//+o-/++:-://:----oMMMMMMMMMNNNNNNNNdyyymNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMd  /ssssssssssssssssssssssssssssssssssooooooooossssoooosoooooooooooooooooosoooooooooooooooooo++++++++++++//////////////////////////////////////////////////////////////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++++oo++oooooooooooooooooooooooossssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhdddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddhhhhhhyyyyyyyyyyyyyyyyssssssssssssssssssosooosoooooooooo+ooo++///:/+yss++h++/:-------`   `-oyymNMMMMMMMMMMMMMMMMM
MMMMMMMMMd `/ssssssssssssssssssssssssssssssssssoooosssoooooooooooooooooooooooooooossooooooooooooooooooooooooo+++++++++++++++++/////////////////////////////////////////////////////////////++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo++++oooooooooooooooooooooooooooosssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyhyyhhhhhhhhhhhhhdddddddddddmmmmmmmmmmmmmmmmmmmmdddddddhhhhhhyyyyyyyyyyyyyyyyyyyyssssssssssssssssssoooooooooooooooooooooooooo+++o++++///::--:///+++//:/-/--++mMMMMNNNMMMMMMM
MMMMMMMMMm/oyssssssssssssssssssssssssssssssssssoosssooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++/////////////////////////////////////////////////////++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooo++oooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhddddddddddddmmmmmmmmmmdddddhhhhhhhyyyyyyyyyyyyyyyyyyyyyssssssssssssssssooooooooooooooooooooooooooooooo+++++++++++++++++oooooossyyhhysoydNMMo::NMMMMMM
MMMMMMMMMm/sdyyssssssssssssssssssssssssssssssssooooooooooooooooossooooooooooooooooooooooooooooooosssoooooooooooooooooooo++ooo+++++++++/////////////////////////////////////////////////+++++++++++//++++++++++++++++++++++++++++++++++++++++++++++++++++++oo++ooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhdhddddddddddddddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyysssssssssssssssoooooooooooooooooooooooooooooooooo+++ooo+++++++++++ooooooooosydNMMMMMMMmd-yMMMMMM
MMMMMMMMMd /hsssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooosssoooooooooooooooooooooooooooooo+++++++//////////////////////////////////////////////++/////////////+++++++++++/+++++//+++++++++++++++++++++++++++o++++++++oooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssyyysssyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhddddddhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyssssssssssssosoooooooooooooooooooooooooooooooooooooooooooo+ooo++oooooooooossymMMMMMMmh/oMMMMMM
MMMMMMMMMd.+ysssssssssssssssssssssssssssssssssssssssssoooooooooosssssoooooooooooooooooooooooooooooosoooooooooooooooossssssssssssssssssoo++++++++///////////////////////////////////////////////////////////////////////////++++++++++++++++++++++++++++++++++o+++oooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssysssssssssssyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyysssssssssssssssoooooooooooooooooooooooooooooooo+ooo+oo+++ooo+ooooooooooooooosssymNMMMMso+NMMMMMM
MMMMMMMMMm..yysssssssssssssssssssssssssssssssssssssssooooooooooooossoooooooooooooooooooosssoooooooooooooooooooooooooooossssssssyyyyyyyssooooo+++++++++/////////////////////////////+++++//////////////////////////////////////++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooossssssooosssoossssssssssssssssssssssssssssssssssssssyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyssssssssssssssssssoooooooooooooooooooooooooooooooo+oooooooo+++ooooooooooooooosssssshNMMMMMMMMMMMMM
MMMMMMMMMMy/oyssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooo+++++ooooosssyyyyyyyssssssssssssssyyyysysssooooooo++++++++////////////////////////++++//////////////////////////////////////////////++++++++++++++++++++++++++++++++++++o++oooooooooooooooooooooooooooooooooooooooooooooosssoosooosossssssssssssssssssssssssssssssyyyyyyyhyyhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyssssssssssssoooooooooooooooo+++++++++++++oo++++oooooooooooooooooooooooooooooossssysyMMMMMMMMMMMMMMM
MMMMMMMMMMs-sdysssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooo+++++ooossyyyhhdddhhhhhyyyyyyssssssssssssssoooooooooooo++++++++++////////////////////////+////////////////////////////////////////////////////////+/++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooossoooooossssooooooossssssssssssssssyyyyyyyhhhhhyhhhhhyyyyyyyyyyyyyyyyyyyyyyyyysssssoooooooo++++++++++++++++++++++++++++++++++oooosssyyyyyysssooooooooooooosyyyhhhyNMMMMMNNmdMMMMMM
MMMMMMMMMMmsymysssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooo+++o+ooossyyyyhhhhhyyyyysysssyyyyysssssssssoosooooooooooo++ooo+++++++++//////////////////////////++////////////////////////////////////////////////////////////////+++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhyyyyysssoooo+++++++//////////////+++++++++oooooosssyyyhhhdddddhhhhyyyssoooooosssyhhhmNNmdNMMMMmd:sMMMMMM
MMMMMMMMMM/:yhyssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooosyhhhhhdhhyssoooo+++ooosssssssssssssooooooooooo++++++++ooo++++++++/////////////////++++//+///++++///////////////////////////////////////////////////////////////////++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhyysssoo++++///////////////+++++ooooossyyyhhhhhddddmmmmmmmmdddhhyysssoooossyyyyso----+ymMMMNmyomMMMMMM
MMMMMMMMMM:`:syssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooosyyhhddhyyso++++++++++ooossssssssssssooooooooo++++++++++++++++++++++/////////////////++++///////+++////////////////////////////////////////////////////////////////////////++++++++++++++++++++++++++++++++++++++o++oooooooooooooooooooooooooooooooooooooo+ooooooooooooooooooooossssssssssssssyyyyyyyyyyyyyyhhhhhhhhhdddhhhhyyyssoo++////////+++++++oooossssyyhhhhdddddmddddddddddhhyysssooo+oooosssso-`sssmNNMMMMMMMMMMMMMMMMM
MMMMMMMMMMm/:.+ysssssssssssssssssssssssssssssssssssooosssoooooooooooooooooo++oooooossyyhhhhhyso++//++++++++oooossssssssssssssssssooo+++++++++++++++++++++/////////////////++////////////////////////////////////////////////////////////////////////////////////+++++++++++++++++++++++++++++++++++++++++++ooooooooooooooo++oooooooooooooooooooooooooooooooooooooooooooosssssssssssyyyyyyyyyyyyhhhhhhhddddddddddddhhhyyssoo+++++++oooossssssyyyyyhhhhhhhhhhhhhhhyyyyssooo++++oosssssssyoo:-sNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs:`syssssssssssssssssssssssssssssssssssssssssssoooooooooooooooo+++ooooosyhhhhhhyso+++//++++++oooosssssssssssssyyyhhhhyysooo++++++++oo++++++++//////////////////++///++////+////////////////////////////////////////////////////::://///////////////+++++++++++++++++++++++++++++++++++++++++++++++++++++++o+++++++oooo+++++++o+++++++++oooooooooooooooooossssssssssssssssyyyyyyyyyhhhhhhddddddddddddddddhhhhyyyysssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssysssssyyyhhhyyysy+:/yNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM+:`.syssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooo++ooosyhhddhyys+++++++++ooooossssssyyyyyhhhdddddddhhyso+++/+++++ooo+++++++++++//////////////+++//////////////////////////////////////////////////////////////:////::://///////////////+++++++/////////////++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o++oooooooooooooooooooosssssssssssyyyyyyyhhhhhhhhhddddddddddddddhhhyyyyyyyyyyyyyyyyyyysssyyyyssssssssysyyyyyyhhhhhhhdhhhhyysoo/ydmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMy. .ssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooo+++oosyhhddhhyso+++++++++oooossssyyyhhhhddddmmddddhyyso+///++++oossoooo+++++++++////////////////////////////////////////////////////////////////////////////////:::////////////////////////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooossssssssssyyyyyyhhhhhhhhhddddddddddhhhhhyyyyssssssssssssssssssssssssssssssssyyyyhhhhhhdddddddhyss++++//dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMh` .ssssssssssssssssssssssssssssssssssssssssssssssssssssooooooo+++oosyhhhhhysso++++++++oossssyyyhhhhhddddddddddhhysoo++//+++oosyyyssoo++++++++++++////////////////////////////////////////////////////++++++++/+/////////////////////////////////////////////////////////////////////+++++++++++++++++++++++++++++++++++++++++++++++++o++++++++oooooooooooooooosssssssssyyyyyhhhhhhddhhhhddddhhhhhhyyyysssssssssssssssssssssssssssssssssyyhhhhhddddddddmdddhhyyyssso+-oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMN+ `sssyyyyyyyssssssssssssssssssssssssssssssssssssssssssssoooo++++osyyhhhyysooo+++++++oossyyyhhhhdddddddddddhyysoo+++++++oossyyyysso+///////+++++++//////////////////////////////////////////////////++///+++++//////////////////////////////////////////////::///::///////////////////++++++++++++++++++++++++++++++++++++++++++++++oo+++++ooooooooooooooooossssssssyyyyyhhhhhhhdddhhhhhhddhhhhyyyyyssssssssssssssssssssssssssyyyyyyyyhhhddddmmmmmmmmmmmmmmmmmdddhhs://:oMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMo+syssssssssssssssssssssyysssyyyysssyssssssssssssssssssssooo++++ossyhhhyysoo+++++++oosyyyyhhhhddddddddddhhysoo++++++ooosssyyyssoo++//++///+++++++++///////////////////////////////////////++++///++++++++++++//////++/////////////////////////////:::::::::::::::://////////////////////+++++++++++++++++++++++++++++++++++++o+ooooooooooooooooooooooooooossssssssyyyyyhhhhhddddddhhhhhhhhhhhyyyyyysssssssssssssssssyyyyyyyyyyyyyhhhhhdddddmmmmmmmmmmmmmmmmmmmmmmmdddmhdMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNsssssssssssssssssssssysssyyyysssyyyssssssssssssssssssoooo+++ooosyyyyysoo++++++++oossyyyhhhddddddddhhyyoo++////+ooosssooo++++++++oooo+++++++++++++////////////////////////////////////++++///+++++++++++++/////++///////////////////////////////:::::::::///:::////////////////////////+/++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooosssssssyyyyyhhhhddddddddhhhhhhhyyyyyyyyysssssssssssssssyyyyyyyyyyyyyhhhhhhhhhhhdddddddddddddddddddddddddddddo-hNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMmhsssssssssssssssssssssssyyyyyyyyyyyssssssssssssssssssooooo+++ooossyssooo+++++++oosssyyhhhdddmmdddhhyyso++++++oooooo++//://///+++ooooooooo++++++++//////////////////////////////////////////////////////////////////////////////////////////////::::/::/:::::://///////////////////////////+++++++++++++++++++++++++ooooooooooooooooooooooooooooooooossssssyyyyyhhhhddddddddhhhhhhhyyyyyyssssssssssssssssyyyyyyyyyyyyyyyyyyysssssyyyyyyyhhhhhhhhhhhdddddddddddddhhyo/oMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMmssssssssssssssssssssssyyyysyyysyysssssssssssssssssssooooooo+ooosssssoooo++++oooosssyyhhhdddddddhhhyyssssssssssoo++//:////////+++ooooooooo++++++++////////////////////////////////////////////////////////////////////////////////////////////::::::::::://::////////////////////////////////+++++++++++++++++++ooooooooooooooooooooooooooooooooossssssssyyyhhhhhddddddhhhhhhyyyyyyssssssssssssssssssssssssssssssssssoosssssssssyyhhhhhhhhhdddhhddddddddddddddhhhysymMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNo+oosssssssssssssssssyyyyyysssssssssssssssssssssssssoooooooooooooooosooooooooooooossyyyyhhhhhhhhhyyyyyyyyssssoo++////+++++oooooossssoooo++++++++++////////////////////////////////////////////////////////////////////////////////////////::::::::://:////////////////////////////////////++++++++++++++++oooooooooooooooooooooooooooooooooooooosssssssyyyyhhhhddhhhhhhhyyyyyyyyssssssssssssooooooooooooosssssssssyyyyyyyyyyyyhhhhhhhhhhhdddddddddddddddddddhhhhhhhMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNs..+osyysssssssssssssyyyyyyssssssssssssssssssssssssssssoooooooooooossssoooooooooooosssssyyyyyyyyyyysssssoo++++/++++ooossssssssssssoooooo++++++++++/////////////////////////////////////////////////////////////////////////////////////::::::::::://////////////////////////////////++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooosssssssyyyyhhhhhhhyhhhyyyyyyyyyysssssssoooooo++ooooooosssyyyyyyyhhhhyyyyyyyyyhhhhhhhhhhhhhddhhddddddddddddddddddhmNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMsh--+sssssssssssssysyyyyssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooosssssssoooooo+++++++////+++oooossssssssossoosoooooooo+++++////////////////////////////////////////////////////////////////////////////:////::::::::::::::////://///////////////////++++++++++++++oooooooooooooosooooooooooooo+++++++++++ooooooooooooossssssyyyyyyhhhhyyyyyyyyyyyyyyyyysooooo++++++oooooossyyyyyyyhhhhhhhhhyhhhyyyysssyyyyyyyyyyyyyyyyyhhhhddddddddddmdmNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNMy/`-+syyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssssssoooooooooooooooooooooooosooosssssssooo++++++++++++//++++++ooooooooooooooossssoooooooo+++/////////////////////////////////////////////////////////////////////:::::::://::::::::::::::::////////////////////+++++++++++++++oooooosssssssssssssssooooooooo++++++++++++++oooooooooooossssyyyhhhhhhhyyyyyyyyyhhhhyyysssooooo+oooossssyyyyyyyyyysssooooooooooooooo++/:::////////////+++ooosssyyyhhhdddhymMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy-`:osyyyyyyyyyyyssssssssssssssssssssssssssssssssssssssoooooooooooooooooossssssssssssssssssooooooooo++++++++++++++++++++ooooooooooooooooooooo++++++/++++////////////////////////////////////::::::::::////////////::::::::::::::::::::::::::::////////////////++++++++++++++++ooooossssssyyyyyysssssssoooooo+++++++//+++++++++++ooooooosssyyyhhhhhhhyyyyhhhhdddddhhhyysssyyyyyssssssooooooooo+//:::---------:::::--........------------:://++oooossssysshNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.`.+yyyyyyyyyysssssssssssssssssssssssssssssssssssssssooooooooooooooooossssssssssssssssssssssoooooo+++++++///////++++++++ooo++++++++osssssooo++++++++++//++//////////////////////////////::::::::::/:///////////::::::::::::::::::::::::::://///////////////++++++++++oooooooossssssyyyyyyyyyyyyyssssooooo++++//////////++++++oooooossssyyyhhhhhhhhhhdddmmmmmmmmddddhhhso++///:------:--:---...````````........`````````...---......--::///////++++++/++yMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs-.++yyyyyyyyyssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooossssssssssssssoooo+++++//////////++++/////::::---::+syyyyysso++++++++++++++//////////////////////////////:::://///:::::::::::::::::::::::::::::::::::::::://///////////////+++++++++oooooooossssyyyyyyyyyyyyyyyssssoooo+++//////////////++++++ooooossssyyyhhhhhhhhddmmmmmmmmmmdddhyso+/--....`............``````````.....--..........--::::::::::////+++o+++////////:`:yMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+:.+yyyyyyyyyssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooosssoossssssssoooo+++++////////+++++/::----.......-/+shhdhyysoo+++++++++++++/////////////////////////////::://///:://///:::::::::::::::::::::::::::::::::::///////////////++++++++++oooooooosssyyyyyyyyyyyyyyssssooo++++//////:::::////++++++++oooosssssyyyyhhhhhdddmmmmmmdddhhyyso+/:--.........---------....-------::://////::////++oossyssssssyyyyyyysoo+++///////-+mMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`syyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssoooooooooooooooooooooo++oo+++oooooooooooooooooooo++++++++++++++++/::---.........-:+shdddhysoo++o++++++++++++++/////////////////////://:::://////////////::::::::::::::::::::::::::::::::://////////////++++++++ooooooossssssyyyyyyyyyyysssooo+++++//////:://:::://///++++++++ooooossssyyyyyhhhhddddmmdddhhyysssso++////:::://///////////////////+++++++oooo++++ooooossssssssssssssssoo+++++++++++++/`-sdMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.:++syyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssossooooooooooooooooo++++++++++++++++++++++++ooooooooooooooooo++++//::--....---::+sdmmmmdyyso++ooooo+++++++++++//////////////////////////://///////////::::::::::::::::::::::::::::::::::://///////////++++++++ooooooosssssssyyyyyysssoooo++++++///////:::::/:::///++++++++++ooooosssssyyyyyhhhhhdddddhhhhyyssooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooo+---dddMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo++.-ymhyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssoooooooooooooooo++++++++++/////////////++++++++++ooooooooooooo+++///////+osyhddmmmdhhysoo+ooooo++++++++++++++++++//////////////////////////////:/:::::::::::::::::::::::::::::::://///////////////+++++++oooooooooossssssssssssooooo+++++++////////://////////+++++++oooooooosssssyyyyyyhhhhhhhhhhhhyyysssssooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooosssssssssssso/+.+mMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhohMmyyyyyyyyyyyyyyyyyyyyssyyyyyyyyysssssssssssssssoooooooooooooooo+++++++////////////////////+++++++++++++o++ooooosssyyyhhhhhhhhyysooooooooo++++++++++++++++++++///////////////////////////::::::::::::/:::::::::::::::::::::://///////////////+++++++oooooooooosssssssssssssoooo++++++//////////////////++++++++oooooooossssssyyyyyyyyhhhhhhhhhhyyyssssssooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooosssssssssssyyyhs-/MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs.+mNhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssooooossooooooooooo+++++++++/////////////////////////////////++++++oooooooosssssooooooooooooo+++oo+++++++++++++//+++////////////////////////////::::::/:::::::::::::::::::::///://///////////++++++++oooooooooossssssssssssooooo+++++++///////////////++++++++++oooooooooossssyyyyyyyyhhhhhhhhyyyyyysssssooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++oooooossssssyyyyyyyyyyyyh/:MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN--syyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssyysssssssssssoooooooooo+++++++++++//////////////////////////////++++++++++++++++++ooooooooooooooo++oo+++++++++++++++++/////////////////////////////::::://:::::::::::::::::::://////////////////+++++++++oooooooooooossssssssooooo+++++//////////////++++++++++ooooooooooooossssssyyyyyyyyyyyyyyyyyyyyssssssooooooooooo++++++++oooooooo+++++++++++++++++++oooo++++++ooooooooosssssssyyyyyyyyyyyyyhyyydMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs:::-+hhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyddddddddhhhyysssoooooo+++++++++++/////////////////////////++////+++///++++++++++++++++oooooooooooooooo++++++++++++++++++////////////////////////////:::::::::::::::::::://:::://////////////////+++++++++oooooooooooooooooooooo++++++++++++/////++++++++++++ooooooooooooooosssssssyyyyyyyyyyyyyyyyssssssssssooooooooooooooosyhhdddddddddhhhhhyyyysssssssssooooooooooooosssssyyyyyyyyyyyyyyyyhhhhhhhhhhMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:`hNdhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhddhhhdhhdddhyhhhhhysso+++++++///////////////////////////++++++///////++++++++++++++++++++oooooooooooooooo+++++++++++++++++/////////////////////////////////:::::///////////////////////////////++++++++++++++ooooooooooooooooo++++++++++++++++++++++oooooooooooooossooooossssssssssyyyyyyyyyyyyssssssssssssooooooooooosydmNNNNNNNNNmmmmmmmmmdddddddddmmmmddhhysssssssyyyyyyyyyyhhhhhhhhhhhhhhhdddddhhMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/`:ydyyyyyyyyyyyyyyyyyyyyyyyyyhhhhdhhhhhhhhhhhhhhhhhhhhhddddddddsoooo++++++///++////////++///+++/+//+++++++++++++++++++++++++++++++ooooooooooooooooooo+++++++++++++++++//////////////////////////////////////////////////////////////////++++++++++++++++++++++++++ooooo++++++++++ooooooooooooooooooooooooooossssssssssssssssssssyyysyyyyyssssssssssssoooooooooshmNNNNNNmmmmmmddddddddddddddddddddddmmmmNNmmdhhyyyyyhhhhhhhhhhhhhddddddddddmddhmMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmh:-+syyyyyyyyyyyyyyyyyyyyhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddhyso++++//+++//+++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooo++++++++++++++++++/////////////////////////////////////////////////////////////++++++++++++++++++++++++++oo+o+++ooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssooosssoosydmNNNNmmmmmdddddddddddddddddddddddddddddddmmmNNNNmmdhhhhhhhhdddddddddddddddmmmdhymMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/`-yyyyyyyyyyyyyyyyyhhhhhhhhhhhddddddddddddddddddddddddddddddhdddddmhs++++/++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooosooooooooooooooooo++++++++++++++++++++++++++++///////////////////////////////////////////+++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssoooossssydmNNNmmmmdddddddddddddddddddddddddddddddddddddddmNNNNNmmddddddddddddddddddddddmdhy.sMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs.:hdhyyyyyyyyyyyyyhhhhhdddddddddddddmdddddddddddddddddddddddddddddddhso++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooossssssssssssooooooooooo++++++++++++++++++++++++++++++++++//////////+++/+++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssydmNNmmmmmmdddddddhddddddddddddmmmmddddddddddddddddddmmNNNNNmddddddddmmmmmmddddddhy+-.yMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.:+yyhhyyyyyhhhhhhhdddddddddddmmmmddddddddddddddddddddddddddddddhdddddoo+++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooosssssssssssssssssooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssssyhmNNNmmmddddddddddddddddmmmmmmmmmmmmmmmmmmmmmdddddddddddmmNNNNmdddddddmmmmmmddhhys:-/mNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhs.:syyyyyyyhhhhdddddddddmmmddhyso++////////+++osyhddddddddddddddddddddmy+++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooossssssssssssssssssssoooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooo+++++++ooooooooooooooooooooooooooooooossoooooooooossssssssssosssssssossssssssossssssssssssssssssssssssssssssshmNNNmmmdddddddddddmmmmmmmmddhyyssssssyyhddmmmmmmmmmdmdmddddmmNNNmdddddmddddddhhy+.`/NMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh++sssyyyhhhdddddddddmdhyo+//+osyyyyyyyyyso//++/++oyhdddddddddddddddddmhs++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooosssssssssssssssssssssssssssoooooooooooooo+++++++++oooo++ooooo++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooooooooossssoossoooossssssssssssssssssoossssssssooooosssssssossssossssssssssssydNNNmmmmddddddddddmmmmmdhso+//+++ooooooo++/+ooshddmmmmmdmmmddddmmNNmddddddddddhy/-./mMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.syhhhhhhdddddddmdhy+//osyhhhhhhhhyyso:.```.../yso+oyhddddddddhdddddmmdyo+++++++++++++++++++++++++++++++++++++oooooooooooooooooooossssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooo+ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssooosssssssssssooossssoosoooooooooooosssssssssoooooooossssssssymNNNmmmdddddddddmmmmmds+::/+oyysyhdhhdddhhhyso++++oyddmddddmmdddddmNmdddddddddy+yhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNoshhhhdddddddmdds//+sssosshmNNNNNNmh+.```.``.:syhyyo+ohddddddddddddddmmdyo+++++++++++++++++++++++++++++++++++ooooooooooooooooossssssssssssssssssyyssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssooossssssssssoooooooooooooooooooooooosssooooooooooooossososymNNNmmmddddddddmmmmdy+:/++/---:/ymNNNNNNdo/-....-+++ooshddmmdddddddmmmdddddhhhy-:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhhhdddddddmmds/+s+-...--:ymNNNNNmmh+-..-../osyysyhhysooydddddddddddddmmmhs++++++++++++++++++++++++++++++++++oooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooosssssoooosooooooooooooossssssssssssssssssssssssssssoosssssssssssooooooooooooooooooooooooooooooooooooooooooooymNNmmmdddddddddmdmds/:oyo:..--.-/hmNNNNNNNy:` `...../yysoohdddmdddddddmddhhhyys--hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhhddhhddddmdy++ys/-....--:sdNmmmdhhs:/++/:+syydmmNNmhyysoohddddddddddddmmmds+++++++++++++++++++++++++++++o+ooooooooooooooooossssssssssssssssssssssyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssossoosssssssssssoossoooooossssssssssssoooooosssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooosdNNmmmddddddddmmmmy//syyyso+:.--`.:syyhdmmmo.```...:osyyyysoshddddmddddmdhhhyyys--MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhhddddddmmdyoshhss+:-::..--/ydmhyss+/oosooyysymmNNNNmdssyo+sdhddddddddddmmmhs++++++++++++++++++++++++++++ooooooooooooooooooooossssssssssssssssssssssssyyyysyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssosssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooohNNmmmmddddddddmmdo:oyhysyyyss:-/:``:osydmdo.``.:../syyyooyyyoohmdddddddddhhyyyss-`oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyhyhdddddmdmdyoyyyhhyys+:///-..-+ydhhy/ossooyysyhhhdmNNNNmhyys+oddddddddddddmmmdyo+++++++++++++++++++++++++++ooooooooooooooooooooosssssssssssssssssyyssssyyyyyyyyyyyyyyyyyyyyyyyyyyysssssyyyyyyysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssooooossoooooooooooooooooooooooooooooooooooooooooooooooooooooooymNNmmmddddddddmmh//syhmmmmdssyy+:oo:.:shddo.`-/o:-+yyhmmh+oyyysoyddddmmdddhyyyyyys. hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyhddhddddmdhsyyyyyhdhhyyo//+o:..-+o+:/sysosyysyhyyhdmmNmh+:+ss+odhddddddddddmmNmhso++++++++++++oo+++++++oooooooooooooooooooooooooosssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooohNNmmmdddddddmmmh/+soymNNNmmhosyyo/oso:/oo/-:/os::ossyssdmdhdhyysohddddmmddhhhyyysy/ hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhhdddddmmmdyyyyoymNNNmhssso/+ss+-..../+oosyysoddhhhhhyso/-..-+s+sdddddddddddmmNNNdso++++++++++o++++++++++ooooooooooooooooooooooooosssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosdNNmmddddddmmmmh++sosmNNmhyhdhoosys+oso:.-.-+so/+ssoys::+hmhsosyyoshddddmdddhyhhyys/ dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdddddmmdysyysymNmmmmddyssyo+oo+//:/+ossss+:-/+++:-.````....-+oohdhddddddddmmNNNNmy+++++++++++++++++++ooooooooooooooooooooooosssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyhhhhhhyyyyhhhhhhhhyhhhhhhyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooosdNmmdddddddmmmmy+ssshmNmhyyssyh++yys+oo/..-/osssysss+::::+dh+/+ssssyddddmmmdhhhhhysoodMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhhhdddddmmdyyyyohmyyshdmmmhooyyssssoossssssso/.``````..--://////ooydddddddddddmmNNNNh+++++++++++ooooooooooooooooooooooooossssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosdmmddddddddmmmdsos/-/shhyyyysss:-:++osssooossssso//oooo+/+s+-.-:ossydddddmmddhhhhyssNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyhhddddddddhysysoyyssshdmmdds/ossssss+//+osssso::///////:://++oosssydhhdddddddmmmNNNNy+++++++++ooooooooooooooooooooossssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhyyhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssssssoooooooooossssssoooooooooooooooooooooooooooooooosdmmdddddddddmmhss/.`.-----:://-..-+sssssooosossso---::----------:+sshddddmmdddhhhys/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhddddddddysss/-:+ooooo++/:.`:+sssso/..--/ossssss+++osssyyyhhhhyssyddhddddddddmmNNNms++++++++ooo+++ooooooooooooosssssssssssssssssssssyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyysyyssssssssssssssssssssssssssssssssssssssssssssoooooooooooooooooooooooooooooosdmmddddddddmmdhs+-`....-:/-......:ossso+//:/ossso-....-.--------:/oshdddddddddhhys/-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhdddddddddyss+.````````````..-/sssooo///+osssssyyyyyyyhhhyyhyysssoyddhdddddddmmmNNNdo++++++++++++ooooooooooooooooossssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssssssssssssssssssssssssooooossoosssoooooossdmmddddddddddmyso//////+oo+////+ossssso+/:////osssso/////////+++/+oshddddmmmddhys::/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyhhdddddddddhso/..``...-:::///+osssso/+o+//+sssssssoshdhhdmmNNmdysooyddhddddddddmmNNmy++++++++ooooooooooooooossssssssssyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssyysssyssssssssssssssssssssssssydmddddddddddmmhsssssssossssssssyyyyssso+++/--/ossyyyyysssssssssssssshddddmmmdhyyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyhdddddddddhoo+++++/:::://oosyyysssssooo+ossso+/:-/ymmmddmNNNmmo+ssydhhdddddddmmmNNdssoooooooooooooossssyyyyyyhhhhhhhhddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmddddddhhhhyyyhhhhhhhhhhhhhyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyssssyyyyysyyyyyyyyyyydmdddddddddddmhsyyhhhhysssyhhhhys+ossssooo+ossssoossysssyhhhhhyyoooshddddmmmdhyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMohhdddddddddhs/-:/+++ossyyyyyhhys+/osossssssso/-...:+sdmmmNmNNmy:+sshdhhddddmmmmmNmmmdhhyyyssssssyyyhhhddddmmmmmmmmmmmmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmddddddddddddddddddddddddddhhhhhhhhhhhdddhhhddhhddddddddddmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyhhhhyyyyyyyyyyyhmmmddddddddddddyso+shmhyyyhdmmdo/-://osyyysso+::-/ssoooosdmhso+///+shdddmmmmmddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMosyhdddddddddh+--oyyyhyyyhhdddhyo/:---:+sssso+++/:-.--:oydmmmdh//sosdhhhddmmmmmmmmNmmmmNmmmddddhhdddmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddmddddddddddmmmmmmmmmmmmmmmmmNmNNNNNNNNNNNNNNNNNNNNNmNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddhhhhhhhhhhhhhdddhhhhhhhhhhhdmmmddddddddddddh+/:smNddddhmNmh:```.-:+sssso/-..`-+syddmmmmy+....-oyhhddmmmmdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdooydddddddddds:../osyyyyhdmmmdy+-.`-::/osssyyss+/++/-..-/ooo+/:/+ohhhhdddmmmmmmmNNNNmNNMNNNNNNmmmmNmmNmmddmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmddddddddddmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdmddmddmNNNNNNNNMNNMMMMMMMMMMMMmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmdddmmmmdddddddddmmddmddddmddddmddmNNmmddddddmddddds/-:ymmNNmmmds-```--:osssssos+::-`.:ymmNNmdo-````:shhddmmmmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhsshdddddddddhs:...-+hdhhhhhddh+:::++osyhhdhhyyso+/+o/-.`...``--+ydhhddddmmmmmmNNNNNMMMMMMMMMMMMMMMMMMMm-.mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-...........--------osoooooooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMsshNNmNNmdddddddmmddddho..:sdmmNmy/.``-/:-oyyhdhhyss+/o/-.:shmmho-   `-oyhhddmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysyddddddddddhs:-..-+hdmdhhhh+:+osoosyyhmmhhddysys//oso/-.```-/yhhhdddmmmmmmmNMMMNMMMMMMMMMMMMMMMMMMMMMddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddddsssss:::-....   ``                                                         ........................./MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNoNMMdNmmdddddddmdddddh+-.-oyo+/-..-oo/:oyyyhdmNhsyyo+ss+::oo+/.`  `:oyhhdddmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmshyddddddddddhy+:---:oydddho/ossyssyyohmmmmmmdyssys++oss/.`-+yhhhddddmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmdddddddddddddddddddddddddddddddddddddddddddhsssss/:-..      `---------------     `.-:osyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNNmddddddmmddddddho-..-...:+oss++ssydhddmmd+syyssyyso:-.`  `./shhhddddmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo+ydddddddddddhs+:---:/+/::+ssyyyyysohmmmmddddhsosys+/:..:syhhhdddmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNddddysyNNNNNNNNNNNNNNNssyddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmddddddddddddddy/-...:ossy++ysohmmmNmmmy/syyyyyys+.```.:oyhhhddmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhdMMMMMd/dmdddddddddddhys+:----.-/osyyyyyyo/yddmmmddhs::///:..:oyyhhhddmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddmmddddddddddhs/--:ossysyy+ymNNNNmmdo/+syhyso+/``.:oyhhhddddmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyyhdm/hMMMMMMMMNmmddmmdddddhhhhs+/::--:osysyyyyo:/shyyso/:.`````-/oyhyhhddddmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddmmmddddddddddhs+/:-:ooo/:+yyyyyss+---/+o+:...-/syhhdddddmmmNMMMMMMMhs+hyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN..+ydNNMMMMMMMMMMMNmmdmmmmmdddhhhhyso+:::/::oo+:--.--..``````.-/oyyyyhhddddmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmdddddddhys+/::----:----..........-:+syhhhhdddmmmmNNMMMMMMMMMdhd:-ohosMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhdMMMMMMMMMMMMMMMMMNNmmmmmmmmdddhhhhhhyso+//:--........--::+osyyyyhhhdddmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmmmmmmmmdddddddddhhyso+////:::::::://+osyyhhhhddddmmmmNNMMMMMMMMMMMMMMMNmhy+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMNNmmmmmmmmdddddhhhhhhhyyyssoooosssyyyyyyyyhhhddddmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmmmmmmmmmdddddddhhhhhhyyyyyyyyyyhhhhhhddddddmmmmNNMMMMMMMMMMMMMMMMMMMMdysNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM::dNMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmmmmdddddhhhhhhhhhhyyyyyyyhhhhdddddmmmmmmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmmmmmmmmmmmdddddddddhhhhhhhhhhhddddddmmmmmmmNMMMMMMMMMMMMMMMMMMMMMNhy:`dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmosmMMMmymdNMMMMMMMMMMMMMMMMMNNmmmmmmmmmmmmdddddddddddddddddddmmmmmmmmmmmmNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmmmmmmmddddddddddddddddmmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMM/ -:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-::oMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmNNNMMMMMMMMMMMMMMMMMMMMMNNMMMMMMdyhdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyNMmdNMMMMMMMNNNNNNmmmmmmmmmmmmmmmmmmmmmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMdydNNMMdhhds/-:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhMMo`/sddy+++oNMMMMNNyyhdmmmmdddddmmmNNNNNMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNmmmNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhdmMMMMMy+++sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.o/:+NMh-:yyyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhos++++oyhNMMMMMN+++shymdsoooosyMMMMMMMMMMm::::::syMNdsyyyyyhyoooooy///////////---------------------s+----------------ymo-:dmmmmh/::-::::::--:yd/-ymh---`-yhs-------------+s---------------.-mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhoooymMMMMMdyyyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhmNmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm++++++ohyyyyyhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmNMNmmMMMMMMMMMMMMMMMMMMMMMNmNMMmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""";

print("Starting da convertible kernel v3.0...");
time.sleep(2);
print("Loading daconvertible-ubuntu1..");
time.sleep(2);
print("Playing local audio file /daOS/daSystem/daMedia/daMusic.dap..");
time.sleep(1);
print("Merging daconvertible-ubuntu1 with dahead-ubuntu2");
time.sleep(1);
print("Loading da driver modules...")
print("Starting daDesktop...");
time.sleep(3);
print("DaOS successfully booted.");
print("LET'S GOOOOO!!!!!!");
time.sleep(5);
print(dababy_convertible);